title: Blame's Blog
description: Hello

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"

author:
  name: Blame
  avatar: /assets/images/avatar.png
  bio: "A place to record my exp or editorial"

toc: true
toc_sticky: true 

header:
  image: /assets/images/cover.jpg
  nav:
    - title: Home
      url: /
    - title: Tags
      url: /tags/
    - title: About
      url: /about/

sidebar:
  nav: "docs"

markdown: kramdown