title: Blame's Blog
description: Hello

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

paginate: 10
paginate_path: "/page:num/"

permalink: /:year:month:day:title

author:
  name: Blame
  avatar: /assets/images/avatar.png
  bio: "一個只會寫心得的競程菜雞"

markdown: kramdown
kramdown:
  math_engine: mathjax

header:
  nav:
    - title: Home
      url: /
    - title: Blog
      url: /blog/

sidebar:
  nav:
    - main
    - docs

breadcrumbs: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      toc: true
      toc_sticky: true